#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Mon Aug 21 14:00:55 BST 2017
https\://repo.maven.apache.org/maven2/.lastUpdated=1503320455061
https\://repo.maven.apache.org/maven2/.error=
